name: conditional flow
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      
      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: npm-cache-dir-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install
  
      - name: Run tests
        continue-on-error: true
        id: run-tests
        run: npm run fail-test -- --reporter json > test-result.json

      - name: Upload artifacts
        if: steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-result.json