name: container demo
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18
      options: --cpus 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
  
      - name: Run tests
        id: run-tests
        run: npm test

