name: matrix demo
on: 
  workflow_dispatch:
jobs:
  matrix-demo:
    strategy:
      matrix:
        sistema-operacional: [ubuntu-latest, windows-latest]
        nodejs: [12, 14, 18]
    runs-on: ${{ matrix.sistema-operacional }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs }}

      - name: Install dependencies
        run: npm install
  
      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build