name: Path Filter
on: 
  push:
    branches:
      - main
    # paths:
    #   - '**.js'
    paths-ignore:
      - 'docs/**'
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
