name: Workflow Reusable

on:
  workflow_call:
    inputs:
      deploy-to:
        description: "Ambiente que será feito o deploy"
        required: true
        default: "dev"
        type: string
    secrets:
      SUPER_SECRET:
        description: "Super secret"
        required: true
    outputs:
      success:
        description: "Se o deploy foi feito com sucesso"
        value: ${{ jobs.test-job.outputs.outcome }}
jobs:
  test-job:
    name: Run tests
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.set-output.outputs.OUTPUT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install dependencies
        run: npm install

      - name: Deploy to 
        run: echo "Fazendo deploy no ambiente ${{ inputs.deploy-to }}"

      - name: Exibir secrets
        run: |
          echo "Super secret: ${{ secrets.SUPER_SECRET }}"

      - name: Set output
        id: set-output
        run: echo "OUTPUT='sucesso de output'" >> "$GITHUB_OUTPUT"
