name: Workflow Reusable

on:
  workflow_call:

jobs:
  test-job:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install dependencies
        run: npm install