name: Workflow Reusable

on:
  workflow_call:
    inputs:
      deploy-to:
        description: "Ambiente que será feito o deploy"
        required: true
        default: "dev"
        type: string
    secrets:
      SUPER_SECRET:
        description: "Super secret"
        required: true
jobs:
  test-job:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install dependencies
        run: npm install

      - name: Deploy to 
        run: echo "Fazendo deploy no ambiente ${{ inputs.deploy-to }}"

      - name: Exibir secrets
        run: |
          echo "Super secret: ${{ secrets.SUPER_SECRET }}"
