name: Testes secrets

on:
  workflow_dispatch:

env:
    SECRET_ENV: ${{ secrets.SECRET_ENV }}
jobs:
  test-secret-job:
    name: Teste secret
    runs-on: ubuntu-latest
    steps:
      - name: Exibir secrets
        run: |
            echo "Workflow env SECRET_ENV: $SECRET_ENV"
            echo "Super secret: ${{ secrets.SUPER_SECRET }}"

            