name: shared workflow demo

on:
  workflow_dispatch:

jobs:
  shared-job:
    uses: averaacademy/github-site-demo/.github/workflows/reusable.yaml@main
    with:
      deploy-to: "prod"
    secrets: inherit
    
  show-result:
    runs-on: ubuntu-latest
    needs: shared-job
    steps:
      - name: Show result
        run: echo "Deploy foi feito com sucesso? ${{ needs.shared-job.outputs.success }}"