name: shared workflow demo

on:
  workflow_dispatch:

jobs:
  shared-job:
    uses: averaacademy/github-site-demo/.github/workflows/reusable.yaml@main
    with:
      deploy-to: "prod"
    secrets: inherit